DROP TRIGGER IF EXISTS trg_production_block_lineage_prevent_replace ON production_block_lineage;
DROP FUNCTION IF EXISTS prevent_production_block_lineage_replace();
DROP TRIGGER IF EXISTS trg_production_block_lineage_prevent_mutation ON production_block_lineage;
DROP FUNCTION IF EXISTS prevent_production_block_lineage_mutation();
DROP TRIGGER IF EXISTS trg_production_document_blocks_prevent_replace ON production_document_blocks;
DROP FUNCTION IF EXISTS prevent_production_document_block_replace();
DROP TRIGGER IF EXISTS trg_production_document_blocks_prevent_mutation ON production_document_blocks;
DROP FUNCTION IF EXISTS prevent_production_document_block_mutation();
DROP TRIGGER IF EXISTS trg_production_document_versions_prevent_replace ON production_document_versions;
DROP FUNCTION IF EXISTS prevent_production_document_version_replace();
DROP TRIGGER IF EXISTS trg_production_document_versions_prevent_mutation ON production_document_versions;
DROP FUNCTION IF EXISTS prevent_production_document_version_mutation();
DROP TRIGGER IF EXISTS trg_production_evidence_snapshots_prevent_replace ON production_evidence_snapshots;
DROP FUNCTION IF EXISTS prevent_production_evidence_snapshot_replace();
DROP TRIGGER IF EXISTS trg_production_evidence_snapshots_prevent_mutation ON production_evidence_snapshots;
DROP FUNCTION IF EXISTS prevent_production_evidence_snapshot_mutation();
DROP TRIGGER IF EXISTS trg_production_evidence_snapshots_prevent_frozen_insert ON production_evidence_snapshots;
DROP FUNCTION IF EXISTS prevent_frozen_production_evidence_insert();
DROP TRIGGER IF EXISTS trg_production_source_items_prevent_frozen_write ON production_source_items;
DROP FUNCTION IF EXISTS prevent_frozen_production_source_item_write();
DROP TRIGGER IF EXISTS trg_production_source_sets_prevent_frozen_delete ON production_source_sets;
DROP FUNCTION IF EXISTS prevent_frozen_production_source_set_delete();
DROP TRIGGER IF EXISTS trg_production_source_sets_prevent_reopen ON production_source_sets;
DROP FUNCTION IF EXISTS prevent_frozen_production_source_set_reopen();

ALTER TABLE IF EXISTS production_documents DROP CONSTRAINT IF EXISTS fk_production_documents_latest_approved_version;
ALTER TABLE IF EXISTS production_documents DROP CONSTRAINT IF EXISTS fk_production_documents_current_version;

DROP TABLE IF EXISTS production_block_lineage;
DROP TABLE IF EXISTS production_document_blocks;
DROP TABLE IF EXISTS production_document_versions;
DROP TABLE IF EXISTS production_documents;
DROP TABLE IF EXISTS production_evidence_snapshots;
DROP TABLE IF EXISTS production_source_items;
DROP TABLE IF EXISTS production_source_sets;

ALTER TABLE production_document_types DROP CONSTRAINT IF EXISTS uq_production_document_types_id_tenant;
ALTER TABLE production_projects DROP CONSTRAINT IF EXISTS uq_production_projects_id_tenant;
